project:
  name: quickstart-autodesk-forge
  owner: quickstart-eng@amazon.com
  package_lambda: false
  shorten_stack_name: true
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  forge-nodejs:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      BastionAMIOS: Amazon-Linux2-HVM
      BastionInstanceType: t2.micro
      EnableBastionHost: Disabled
      ForgeClientId: override_this
      ForgeClientSecret: override_this
      ForgeNodeInstanceType: t2.micro
      ForgeAppName: forge-viewmodels-nodejs-aws
      ForgeApplicationRuntime: "Node.js"
      ForgeNodesDesiredCapacity: '2'
      ForgeNodesMaxSize: '4'
      ForgeNodesMinSize: '2'
      KeyPairName: $[taskcat_getkeypair]
      OperatorEmail: forge-test@example.com
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-autodesk-forge/
      RemoteAccessCIDR: 10.0.0.0/16
      VPCCIDR: 10.0.0.0/16
    regions:
      - ap-northeast-1
      - ap-south-1
      - ap-southeast-2
      - eu-central-1
      - eu-west-2
      - us-east-1
      - us-west-2
    s3_bucket: ''
    template: templates/autodesk-forge-main.template.yaml
  forge-netcore:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      BastionAMIOS: Amazon-Linux2-HVM
      BastionInstanceType: t2.micro
      EnableBastionHost: Disabled
      ForgeApplicationRuntime: ".NET Core"
      ForgeAppName: forge-viewmodels-netcore-aws
      ForgeClientId: override_this
      ForgeClientSecret: override_this
      ForgeNodeInstanceType: t2.micro
      ForgeNodesDesiredCapacity: '2'
      ForgeNodesMaxSize: '4'
      ForgeNodesMinSize: '2'
      KeyPairName: $[taskcat_getkeypair]
      OperatorEmail: forge-test@example.com
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-autodesk-forge/
      RemoteAccessCIDR: 10.0.0.0/16
      VPCCIDR: 10.0.0.0/16
    regions:
      - ap-northeast-2
      - ap-southeast-1
      - ca-central-1
      - eu-west-1
      - eu-west-3
      - us-east-2
      - us-west-1
    s3_bucket: ''
    template: templates/autodesk-forge-main.template.yaml